### PR TITLE
changes needed for xml parsing

### PR DESCRIPTION
**Pull request by oli-obk**
I'm starting to work on a separate crate at https://github.com/oli-obk/serde-xml

cc #39 
cc #68

### CODE REVIEW

**Comment by oli-obk** [comment]
rebased over 206e19edb40a8e3df29fc8d3862d92b02176f3dc

**Comment by erickt** [comment]
It's a shame that `NumericVisitor` and `PrimitiveVisitor` are nearly identical. I suppose we should just drop `PrimitiveVisitor` since most things will need to be parsable from a string.

On making `LineColIterator` always peekable, could you instead make it that it's only peekable if it's wrapping a peekable iterator?

Other than that looks good. Sorry it took me so long to get to this!

**Comment by oli-obk** [comment]
done, but this makes using the `get_mut` and `get_ref` functions quite dangerous when used with a peekable `Iterator`

**Comment by oli-obk** [comment]
@erickt I remember why I added NumericVisitor instead of modifying PrimitiveVisitor: enums!

```
benches/bench_log.rs:85:15: 85:56 error: the trait `core::str::FromStr` is not implemented for the type `HttpProtocol` [E0277]
benches/bench_log.rs:85         state.visit(de::impls::PrimitiveVisitor::new())
```

**Comment by erickt** [comment]
Thanks and sorry for the long delay!

**Pull request merged**
