### PR TITLE
Errors redesign

### LINKED ISSUE #528: Deserialization errors like "Error: Invalid type. Expected `I64`" are hard for users to understand
Thank you for your help parsing mixed strings and structs! Here's a second issue to think over. :-)

Here, I'm parsing a 1,300-line `docker-compose.yml` file which uses bare string notation, and which therefore sometimes accidentally uses an integer value like `1` where it should have used a string:

``` yaml
version: 2
services:
  foo:
    environment:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: 1
      REDIS_URL: redis://redis:6379
```

I deserialize this with the following declaration:

``` rust
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty",
            deserialize_with = "deserialize_map_or_key_value_list")]
    pub environment: BTreeMap<String, String>,
```

The function `deserialize_map_or_key_value_list` contains a `visit_map` function which calls `visitor.visit_value::<String>()` to read a string.

When I run this program over the 1,300 line input file, it gives me the following error:

```
target/debug/examples/normalize < docker-compose.yml > test.yml
Error: Invalid type. Expected `I64`
```

There are several problems here:
1. The error message should be the "other way around", and include both the expected type and the one we actually got.
2. The error message should ideally include a line number so the user knows where in the enormous file the error occurs.
3. The error message should include the actual I64 value.

This would ideally give us something like:

```
<input>:869: Expected String, got I64 value `1`.
```

This would make my program much more user friendly. :-) I can easily provide a slightly better workaround in this particular case, but I'd love to find a more general solution.

### LINKED ISSUE #675: Remove de::Error::end_of_stream
Currently this is used in the following cases:

- Tuple or fixed-size-array being deserialized and there are not enough values in the SeqVisitor. This is better served by `invalid_value`. We may be nowhere near the end of the input stream.
- Char being deserialized from an empty string. Again this is definitely `invalid_value`.
- A Value deserializer being misused...? This will be rendered impossible by #651.
- Generated code for an enum. As in... it's there in the generated code. But it is unreachable. Interesting.

The `de::Error` constructors are designed to be used from the Visitor of a Deserialize type. I struggle to think of any valid reason that a Visitor would think it is in an end_of_stream situation.

Note that Deserializers construct their own errors however they want without going through the `de::Error` constructors, so those can keep returning errors that are equivalent to end of stream. For example JSON uses EOFWhileParsingValue for this purpose.

Overall I would like to focus on improving the messages from invalid_type / invalid_value which I am doing as part of #528. I don't think end_of_stream means anything.

### LINKED ISSUE #702: Reconsider MapVisitor::missing_field
Out of all the Serde deserializers on GitHub, there are exactly four distinct behaviors for missing_field:

- Unconditionally an error
- For options treat it as None, otherwise error
- Treat it as unit
- [Whatever serde_xml is doing](https://github.com/serde-rs/xml/blob/f9330b703c7405ea8f54e1adfa972cb869924e38/src/de/value.rs#L358-L382)

Ideally I would like to standardize on one of these (my preference is None/error) and remove the ability for deserializers to modify the behavior. This would improve consistency and predictability across the ecosystem.

@oli-obk can you explain the various cases that serde_xml needs to handle in missing_field and whether you can think of any alternative ways to accomplish this?

### LINKED ISSUE #709: Remove Visitor::visit_unit_struct
This is a bizarrely placed API. For tuple structs we go deserialize_tuple_struct -> visit_seq, for braced structs we go deserialize_struct -> visit_map. Neither of these involves passing the &'static str name of the struct back into the Visitor. It would be more consistent to remove visit_unit_struct and have unit structs go deserialize_unit_struct -> visit_unit.

### PR DESCRIPTION
**Pull request by dtolnay**
Fixes #528 and fixes #675 and fixes #709 and fixes #702..

Essentially we rely on every Visitor to tell us what type of data it is expecting. See the doc comments in serde/src/de/mod.rs.

In general my goal is to centralize error message building in Serde rather than leaving it to each individual format to reimplement lousy messages. This is a step in that direction and I have a design for https://github.com/serde-rs/json/issues/173 which I will implement in another PR.

### CODE REVIEW

**Comment by dtolnay** [comment]
@oli-obk this is stable enough to review when you have time. I need to follow up on some TODOs in serde/src/de/impls.rs related to invalid_length which I will take care of tomorrow.

**Comment by dtolnay** [comment]
Some of the error messages in the tests are wonky because of the bug in #711.

> "unknown field \`b\`, expected \`a\` or \`b\`"
> "unknown variant \`Skipped\`, expected one of \`Skipped\`, \`Unit\`, \`Simple\`, \`Seq\`, \`Map\`"

I will merge that fix into this branch and update the tests.

**Comment by dtolnay** [comment]
I merged the MapVisitor::missing_field change from #706 into this branch so I have something to tag and work against for serde_json.

**Comment by oli-obk** [comment]
awesome redesign. This will also greatly improve the errors reported on no-std builds.

**Comment by Arnavion** [comment]
I have 0.8 code like:

```rust
impl Deserialize for Foo {
    fn deserialize(...) {
        struct Visitor;
        impl Visitor for Visitor {
            fn visit_str(&mut self, v: &str) {
                some_operation.map_err(|err| Error::invalid_value(err.description()))
            }
        }
    }
```

Where does the underlying error description go in 0.9?

If it goes in the `Unexpected` parameter, that means I would need to use `Unexpected::Other` instead of `Unexpected::Str`:

```rust
fn visit_str(self, v: &str) {
    some_operation.map_err(|err| {
        Error::invalid_value(Unexpected::Other(&format!("{} - {}", s, err.description())), &self);
    })
}
```

If it goes in the `Expected`, then I can use `Unexpected::Str` for the first parameter but the second parameter becomes harder:

```rust
fn expecting(&self, f) {
    f.write_str("a string that can be deserialized into a Foo")
}

fn visit_str(self, v: &str) {
    some_operation.map_err(|err| {
        // can't reuse `expecting` directly since we don't have a Formatter
        let expected = format!("a string that can be deserialized into a Foo - {}", err.description());
        Error::invalid_value(Unexpected::Str(s), &&*expected);
    })
}
```

unless I have some other method that returns the string and use it in both `expecting` and `visit_str`, or I stash the description as a property of `Visitor` and read it in `expecting`.

Maybe `invalid_value` etc could take a third `reason: Option<Display>` parameter?

**Comment by dtolnay** [comment]
@Arnavion I would prefer to use Error::custom for this.

```rust
Error::custom(format!("invalid Foo {:?}: {}", s, err.description()))
```

Compare:

> invalid value: string "xyz", expected a string that can be deserialized into a Foo - string must start with "F"

> invalid Foo "xyz": string must start with "F"

What do you think?

**Comment by Arnavion** [comment]
Yes, I suppose. It's a shame that `expecting` goes to waste.

**Pull request merged**
