### PR TITLE
Improves `u128`/`i128` handling 

### PR DESCRIPTION
**Pull request by bkchr**
Besides that it makes it possible to have `u128`/`i128` in buffered `Content`.

### CODE REVIEW

**Comment by c410-f3r** [comment]
ping @dtolnay
ICE was probably fixed by [#66669](https://github.com/rust-lang/rust/pull/66669) and latest nightly now compiles the serde test suite

**Comment by c410-f3r** [comment]
ping @bkchr @dtolnay 

What is the status of this PR? If possible, I would like to tackle any kind of problem that is blocking this fix.

**Comment by bkchr** [comment]
Yeah, I'm waiting for a review :)

**Comment by frol** [comment]
@dtolnay We have bumped into https://github.com/serde-rs/json/issues/505 issue which is supposedly resolved by https://github.com/serde-rs/json/pull/586 which seem to require this PR to be merged. I wonder if this is considered by design or it will eventually be fixed

Thank you for your hard work!

**Pull request closed without merging**
