### PR TITLE
de: Make flattened structs and aliases interact correctly.

### LINKED ISSUE #1504: Field aliases do not work in combination with `flatten`
Field aliases as introduced in https://github.com/serde-rs/serde/pull/1458 do not work when deserializing "flattened" structures.

### Expected behavior

Field aliases should work when deserializing "flattened" structures.

### Observed behavior

Field aliases do not work when deserializing "flattened" structures.

### How to reproduce

The following code can be used to reproduce the problem, also available as Rust Playground snippet [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2a24a58747f7c27840774e2492fa5d1e).

```
use serde::{Deserialize, Serialize};
use serde_json;

#[derive(Serialize, Deserialize)]
pub struct A {
    #[serde(rename = "y", alias = "z")]
    x: i64,
}

#[derive(Serialize, Deserialize)]
pub struct B {
    #[serde(flatten)]
    a: A,
}

fn main() -> Result<(),Box<std::error::Error>> {
     let i = r#"{ "z": 12 }"#; // using r#"{ "y": 12 }"# will work.
     let b: B = serde_json::from_str(i)?;
     assert_eq!(b.a.x,12);
     Ok(())
}
```

### PR DESCRIPTION
**Pull request by jhoobergs**
Rebased version of https://github.com/serde-rs/serde/pull/1519

@dtolnay What would be needed to get this merged?

Fixes #1504

### CODE REVIEW

**Comment by jhoobergs** [comment]
@dtolnay Any thoughts?

**Comment by PhotonQuantum** [comment]
So what's the progress of this PR? The related issue has been locked and there's no review activity on this one.

**Review by dtolnay — COMMENTED** [review]
https://github.com/serde-rs/serde/pull/1519#pullrequestreview-233751469 is still the approach that I would prefer. I guess this got stuck on @emilio (or anyone else) looking into what the practical downsides of that approach might be. As far as I can tell it doesn't cause any issue with bincode.

**Comment by dralley** [comment]
https://github.com/serde-rs/serde/pull/2387 claims to fix #1504 also

**Review by dtolnay — COMMENTED** [review]
Fixed a different way by #2387.

**Pull request closed without merging**
