### PR TITLE
YAML Support [WIP-DO NOT MERGE]

### PR DESCRIPTION
**Pull request by Byron**
This PR provides a link to the ongoing implementation of YAML support, and shall be used to ease communication to the `serde` maintainers.

We should use it to enter a dialogue about implementation questions, and as a means for reviewing code as it is being created.

# The Development Workflow

The fork I am working on is using [issues](https://github.com/Byron/serde/issues) to track current tasks, and [milestones](https://github.com/Byron/serde/milestones) to show overarching goals. For that reasons, each issue is assigned a corresponding milestone.

All development is recorded and youtube links are posted to the respective issue once the upload has completed.

### CODE REVIEW

**Comment by blaenk** [comment]
I'm interested in this. I hope it goes well.

**Comment by erickt** [comment]
This is awesome! Can't wait to see it finished.

**Comment by Byron** [comment]
Just to give you a little heads-up: I am sick right now and try hard to get better. Additionally I just bought `The Witcher 3` and hope to find a good balance between doing a few sessions of YAML, and being sucked into an intense game world.
The goal is to get back into this project from tomorrow, let's see about that.

**Comment by Byron** [comment]
I am withdrawing this PR as all development moved to [the dedicated repository](https://github.com/serde-rs/yaml).

**Pull request closed without merging**
