### PR TITLE
Add Serde impls for i128 and u128

### PR DESCRIPTION
**Pull request by dtolnay**
Fixes https://github.com/serde-rs/serde/issues/1136.

### CODE REVIEW

**Comment by cgm616** [comment]
What's the process like to get this merged? Support for i128 and u128 would be awesome.

**Comment by dtolnay** [comment]
I am planning to land this on 25 May to give people some time to complain about our new build script. It becomes complicated to reverse course on the build script after starting to stick observable behavior behind it.

**Comment by dtolnay** [comment]
@oli-obk can you notice any problems with this approach?

**Comment by dtolnay** [comment]
Thanks, I really appreciate the second opinion. In terms of CI -- our existing 1.13.0 builder confirms that things continue to compile on a compiler without these types. Our nightly builder that runs the test suite is running test_de::test_small_int_to_128 and test_ser::test_integer128. The usefulness of those test cases is limited by not having 128-bit tokens in serde_test (#1281) but at least they confirm that deserialize_?128 and serialize_?128 are invoked as intended. Upon implementing #1280 at least there will be a Deserializer directly in the Serde codebase that deals with 128-bit integers that can be tested. And serde_json will provide end-to-end test coverage when we add 128-bit support there.

**Pull request merged**
