### PR TITLE
Delete serde_macros

### LINKED ISSUE #565: Delete serde_macros
This requires moving the compile-tests over to the serde_derive crate.

### PR DESCRIPTION
**Pull request by dtolnay**
Fixes #565.

### CODE REVIEW

**Comment by dtolnay** [comment]
Unfortunately compiletest can't do multi-line error messages, so I had to do this:

```rust
#[derive(Serialize)] //~ ERROR: custom derive attribute panicked
#[serde(abc="xyz")] // ERROR: unknown serde container attribute `abc`
struct A {
    x: u32,
}
```

We are only checking that the thing fails to compile because "custom derive attribute panicked", not the specific message. I left the messages there so that it is clear what is being tested.

**Comment by oli-obk** [comment]
> Unfortunately compiletest can't do multi-line error messages

What do you mean by multi-line error messages?
Multiple ones per line? Or error messages with a span going over multiple lines?

**Comment by dtolnay** [comment]
Here is what the message looks like:

```rust
error: custom derive attribute panicked
 --> src/main.rs:9:10
  |
9 | #[derive(Serialize)]
  |          ^^^^^^^^^
  |
  = help: message: unknown serde container attribute `abc`
```

Compiletest only sees the error at the top, not the "help". I think related to https://github.com/rust-lang/rust/issues/31380.

**Comment by oli-obk** [comment]
Compiletest only sees a help when you ask for a help in the code. So adding a //~^ HELP below the error line should work

**Comment by dtolnay** [comment]
Good call, I didn't know about that. I pushed a fix.

**Pull request merged**
