### PR TITLE
Impl Serialize/Deserialize for std::ops::{Bound, RangeFrom, RangeTo, RangeToInclusive}

### PR DESCRIPTION
**Pull request by 0nkery**
Implemented `Serialize` and `Deserialize` traits for various interval-related types from `std`.

Could help me to setup `cfg`s etc properly?

### CODE REVIEW

**Comment by dtolnay** [comment]
Could you explain more about your use case for these impls? How is all of this going to be used in what you are building?

**Comment by 0nkery** [comment]
Yep, that's right.

**Comment by dtolnay** [comment]
Thanks, I merged the PR but pared it down to just the Bound impls in a later commit. I am not opposed to the other impls but I would prefer not to accept code that I don't know of anyone wanting to use.

Published in 1.0.86.

**Comment by 0nkery** [comment]
Thanks! We've decided to use `Bound` only anyway.

**Pull request merged**
