### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by thorbenk**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a144fc3ef7a5d0277723f014152844a7d7fb709f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/serde-rs/serde

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a144fc3ef7a5d0277723f014152844a7d7fb709f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: a107be30699610d8d2de713146d3e26602b04596
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/serde-rs/serde

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e5beef4004b479a00ad2747b89fe84957c961fb4
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/serde-rs/serde

---
This message was auto-generated by https://gitcop.com

**Comment by erickt** [comment]
Thanks!

**Pull request merged**
