### PR TITLE
fix(#151): renaming Deserializer::visit_* to Deserializer::deserialize_*

### PR DESCRIPTION
**Pull request by oli-obk**
serde-json PR @ https://github.com/serde-rs/json/pull/13

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ed9b076e4cc8f9634d20d392579e0ff867ddbba8
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/serde-rs/serde

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ed9b076e4cc8f9634d20d392579e0ff867ddbba8
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 9a6e5be006639a726bc8d5903efb0861f0499546
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/serde-rs/serde

---
This message was auto-generated by https://gitcop.com

**Comment by erickt** [comment]
Looks good, other than the test failing. Could you update it?

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 71a9fadadc1e5520fc39a47e5525002c03a1ea00
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 057bc00ac8d22ab21a2746dad1fbe98c62aa7476
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: f4bf85eddfffc97aebd4314ee8b3dbd5647a2f83
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/serde-rs/serde

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e05737a93c3fc83f4530d89b0891db76c9a43ec6
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/serde-rs/serde

---
This message was auto-generated by https://gitcop.com

**Comment by oli-obk** [comment]
is there a way to make gitcop automatically delete its obsolete messages?

**Comment by oli-obk** [comment]
test passes now

**Comment by erickt** [comment]
@oli-obk: Shucks, just broke it on you again :(

**Comment by erickt** [comment]
@oli-obk: and no, I'm not sure if there's much we can do about those gitcop messages. I'm exploring if there are better options that we can use. Philosophically I like it, but practically it can be a bit obnoxious and I'm not sure if it's worthwhile.

**Comment by oli-obk** [comment]
fixed

wrt gitcop: I found it very confusing to figure out how to properly write a commit message. (like what is "scope"?)

**Pull request merged**
