### PR TITLE
Xml

### PR DESCRIPTION
**Pull request by oli-obk**
would you be so kind as to review the `serde_macros` and `Deserializer` changes?

current state:
- [x] xml to struct deserialization
- [x] deserialize bool, int, string from `<anytagname>value</anythingelse>`
- [x] deserialize sequences (tuple, array, vector) as struct member
- [x] deserialize escaped chars (`&abcd;`)
- [x] deserialize CDATA
- [ ] deserialize enumerations
- [ ] deserialize arrays of enumerations
- [ ] deserialize errors instead of assertions
- [ ] more deserialize tests
- [x] parse to dom tree
- [ ] remove debug print! messages
- [ ] struct to xml serialization

anti-features (just ignoring stuff I don't like):
- [x] ignore namespaces
- [x] skip xml comments
- [x] skip xml version tag
- [x] ignoring xml-attributes

things that would be nice to have but might not be possible
- [ ] xsd verification
- [ ] sequences of sequences (how would these even look like in xml?)
- [ ] attributes to collapse xml elements that only contain a single type of element.

### CODE REVIEW

**Comment by erickt** [comment]
First off this is awesome. I'll go through it tonight. Second, I was actually thinking about factoring json out into a separate crate as folks might not want json, or someone might come up with a better one down the road. What do you think?

**Comment by oli-obk** [comment]
I've read about cargo having a few problems with multiple inheritance. Someone might be using `xml` and `json` crates that require different `serde` versions, which might get messy. This needs to be checked.

**Comment by oli-obk** [comment]
Also: someone implementing a better/different json-deserializer won't have a conflict. During deserialization you choose which Deserializer to use; Rust doesn't care/know that two Deserializers deserialize the same format.

**Comment by oli-obk** [comment]
@erickt there are a few xml-specific things I'd like to discuss. Should I start a thread on [the rust user forum][1] or a wiki entry or an issue here?

   [1]: http://users.rust-lang.org

**Comment by erickt** [comment]
@oli-obk: Hi there! Sure, a thread would be wonderful. And in case you haven't noticed, I've been slowly pulling bits and pieces from your PR, so thanks for all the hard work so far!

**Comment by oli-obk** [comment]
http://users.rust-lang.org/t/rfc-serde-xml-support/737

Yea I noticed, thanks. Although after merging Xml, some coverage checks would probably be good to figure out if I'm actually using all features I introduced.
Example: I don't think the `end` function of Sequences and Maps ever needs to be implemented. All the code could be in `SeqVisitor::visit_value` or `MapVisitor::visit_key`. Then again, it might be more readable to put it in `end`

**Comment by oli-obk** [comment]
separating it out into its own crate isn't really working, and I don't know why:

```
D:\rust-serde\xml\tests\test_xml.rs:112:5: 112:18 error: the trait `serde::ser::Serialize` is not implemented for the type `Simple` [E0277]
D:\rust-serde\xml\tests\test_xml.rs:112     test_parse_ok(&[
                                            ^~~~~~~~~~~~~
D:\rust-serde\xml\tests\test_xml.rs:112:5: 112:18 error: the trait `serde::de::Deserialize` is not implemented for the type `Simple` [E0277]
D:\rust-serde\xml\tests\test_xml.rs:112     test_parse_ok(&[
                                            ^~~~~~~~~~~~~
D:\rust-serde\xml\tests\test_xml.rs:135:5: 135:18 error: the trait `serde::ser::Serialize` is not implemented for the type `test_parse_xml_value::Test` [E0277]
D:\rust-serde\xml\tests\test_xml.rs:135     test_parse_ok(&[
                                            ^~~~~~~~~~~~~
D:\rust-serde\xml\tests\test_xml.rs:135:5: 135:18 error: the trait `serde::de::Deserialize` is not implemented for the type `test_parse_xml_value::Test` [E0277]
D:\rust-serde\xml\tests\test_xml.rs:135     test_parse_ok(&[
                                            ^~~~~~~~~~~~~
D:\rust-serde\xml\tests\test_xml.rs:146:5: 146:18 error: the trait `serde::ser::Serialize` is not implemented for the type `Outer` [E0277]
D:\rust-serde\xml\tests\test_xml.rs:146     test_parse_ok(&[
                                            ^~~~~~~~~~~~~
D:\rust-serde\xml\tests\test_xml.rs:146:5: 146:18 error: the trait `serde::de::Deserialize` is not implemented for the type `Outer` [E0277]
D:\rust-serde\xml\tests\test_xml.rs:146     test_parse_ok(&[
                                            ^~~~~~~~~~~~~
D:\rust-serde\xml\tests\test_xml.rs:210:5: 210:18 error: the trait `serde::ser::Serialize` is not implemented for the type `test_parse_attributes::A` [E0277]
D:\rust-serde\xml\tests\test_xml.rs:210     test_parse_ok(&[
                                            ^~~~~~~~~~~~~
D:\rust-serde\xml\tests\test_xml.rs:210:5: 210:18 error: the trait `serde::de::Deserialize` is not implemented for the type `test_parse_attributes::A` [E0277]
D:\rust-serde\xml\tests\test_xml.rs:210     test_parse_ok(&[
                                            ^~~~~~~~~~~~~
D:\rust-serde\xml\tests\test_xml.rs:226:5: 226:18 error: the trait `serde::ser::Serialize` is not implemented for the type `test_parse_attributes::B` [E0277]
D:\rust-serde\xml\tests\test_xml.rs:226     test_parse_ok(&[
                                            ^~~~~~~~~~~~~
D:\rust-serde\xml\tests\test_xml.rs:226:5: 226:18 error: the trait `serde::de::Deserialize` is not implemented for the type `test_parse_attributes::B` [E0277]
D:\rust-serde\xml\tests\test_xml.rs:226     test_parse_ok(&[
                                            ^~~~~~~~~~~~~
D:\rust-serde\xml\tests\test_xml.rs:262:5: 262:18 error: the trait `serde::ser::Serialize` is not implemented for the type `test_parse_hierarchies::C` [E0277]
D:\rust-serde\xml\tests\test_xml.rs:262     test_parse_ok(&[
                                            ^~~~~~~~~~~~~
D:\rust-serde\xml\tests\test_xml.rs:262:5: 262:18 error: the trait `serde::de::Deserialize` is not implemented for the type `test_parse_hierarchies::C` [E0277]
D:\rust-serde\xml\tests\test_xml.rs:262     test_parse_ok(&[
                                            ^~~~~~~~~~~~~
```

**Comment by nicolai86** [comment]
What's the best way to play around with this pr? I'd like to parse this (http://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist-90d.xml) and all necessary features should be inplace already... :+1:

**Comment by oli-obk** [comment]
@nicolai86 it should work once [rust-quasi is updated to master][1]

  [1]: https://github.com/erickt/rust-quasi/pull/1

**Comment by hugoduncan** [comment]
Updated to latest master and rustc nightly - https://github.com/hugoduncan/rust-serde/tree/oli-obk-xml
Looks like I need "skip xml version tag" to be implemented for this to be useful.

**Comment by oli-obk** [comment]
@hugoduncan: I'm on it wrt skipping comments, version tags and similar. thanks for the rebase, I'll look into it

**Comment by hugoduncan** [comment]
I found I needed to strip `xmlns` attributes from the input.  It might be nice longer term to find a way of annotating the type with it's required namespace and actually produce/verify the `xmlns` attribute.

I also needed to strip whitespace between tags to get input to parse.

**Comment by oli-obk** [comment]
> I also needed to strip whitespace between tags to get input to parse.

do you have an example that doesn't parse? I'll add it as a unit test.

**Comment by oli-obk** [comment]
> I found I needed to strip xmlns attributes from the input. It might be nice longer term to find a way of annotating the type with it's required namespace and actually produce/verify the xmlns attribute.

again, do you have examples and the expected behavior? I don't know much about xmlns :/

**Comment by hugoduncan** [comment]
@oli-obk: an example string:

```
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<DescribeInstancesResponse xmlns=\"http://ec2.amazonaws.com/doc/2014-10-01/\">\n    <requestId>9474f558-10a5-42e8-84d1-f9ee181fe943</requestId>\n    <reservationSet/>\n</DescribeInstancesResponse>"
```

As a first iteration I think it is reasonable to just ignore `xmlns` attributes.

**Comment by oli-obk** [comment]
I think xsd verification is out of scope of serde, but I might be wrong. Anyway, I can silently ignore it.

**Comment by oli-obk** [comment]
your example string works now

**Comment by hugoduncan** [comment]
Another example.  `vpcSet` is a sequence, that can have many `item`s, each of which is a struct with `vpcId` and `state` fields.  Currently I can't seem to construct anything that will deserialise the `item`.  I think this might require some sort of attribute, e.g. `#[serde(rename='item')]`, to set the expected tag name on the struct for `item`.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<DescribeVpcsResponse xmlns="http://ec2.amazonaws.com/doc/2014-10-01/">
    <requestId>8d521e9a-509e-4ef6-bbb7-9f1ac0d49cd1</requestId>
    <vpcSet>
        <item>
            <vpcId>vpc-ba0d18d8</vpcId>
            <state>available</state>
        </item>
    </vpcSet>
</DescribeVpcsResponse>
```

**Comment by oli-obk** [comment]
@erickt: I think I need to extend serde with "fixed size sequences" to get sequences of sequences to work. http://users.rust-lang.org/t/rfc-serde-xml-support/737/9

**Comment by oli-obk** [comment]
@hugoduncan actually this is already possible:
```rust
let s = r#"
<?xml version="1.0" encoding="UTF-8"?>
<DescribeVpcsResponse xmlns="http://ec2.amazonaws.com/doc/2014-10-01/">
    <requestId>8d521e9a-509e-4ef6-bbb7-9f1ac0d49cd1</requestId>
    <vpcSet>
        <item>
            <vpcId>vpc-ba0d18d8</vpcId>
            <state>available</state>
        </item>
    </vpcSet>
</DescribeVpcsResponse>"#;
#[derive(PartialEq, Debug, Serialize, Deserialize)]
#[allow(non_snake_case)]
struct Item {
    vpcId: String,
    state: String,
}
#[derive(PartialEq, Debug, Serialize, Deserialize)]
struct Helper {
    item: Vec<Item>,
}
#[derive(PartialEq, Debug, Serialize, Deserialize)]
#[allow(non_snake_case)]
struct DescribeVpcsResponse {
    requestId: String,
    vpcSet: Helper,
}
test_parse_ok(&[
    (
        s,
        DescribeVpcsResponse {
            requestId: "8d521e9a-509e-4ef6-bbb7-9f1ac0d49cd1".to_string(),
            vpcSet: Helper { item: vec![ Item {
                vpcId: "vpc-ba0d18d8".to_string(),
                state: "available".to_string(),
            }]},
        },
    ),
]);
```

**Comment by oli-obk** [comment]
This would also give you the (in my opinion) expected `response.vpcSet.item[5]` syntax. Not sure if you meant to access `response.vpcSet[5]`. In that case some additional attributes would be required that manipulate the parsing just for xml... I'll add it to the list of maybe stuff.

**Comment by hugoduncan** [comment]
@oli-obk Unfortunately the type can't be called `Item`, as the `item` tag actually gets used for every type of list.  A fuller example that includes `vpcSet` and `tagSet`, both of which are lists, but of different types, and both of which use the `item` tag:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<DescribeVpcsResponse xmlns="http://ec2.amazonaws.com/doc/2014-10-01/">
    <requestId>8d521e9a-509e-4ef6-bbb7-9f1ac0d49cd1</requestId>
    <vpcSet>
        <item>
            <vpcId>vpc-ba0d18d8</vpcId>
            <state>available</state>
            <cidrBlock>10.0.0.0/20</cidrBlock>
            <dhcpOptionsId>dopt-5c61683e</dhcpOptionsId>
            <tagSet>
                <item>
                    <key>Name</key>
                    <value>vpc3</value>
                </item>
            </tagSet>
            <instanceTenancy>default</instanceTenancy>
            <isDefault>false</isDefault>
        </item>
    </vpcSet>
</DescribeVpcsResponse>
```

In this case, I am aiming for `vpc_set[0].tag_set[0].key` syntax to access the data, which seems less redundant to me.

**Comment by hugoduncan** [comment]
Maybe a custom implementation of `Deserialize` can avoid the `item` field.  I'll investigate this.

**Comment by oli-obk** [comment]
I'm afraid it's not that simple. `visit_seq` and the `SeqVisitor` are never exposed

**Comment by oli-obk** [comment]
for now you could use this hack:

```rust
#[derive(PartialEq, Debug, Serialize, Deserialize)]
#[allow(non_snake_case)]
struct VpcSet {
    vpcId: String,
    state: String,
}
#[derive(PartialEq, Debug, Serialize, Deserialize)]
struct Helper<T: PartialEq + Debug + Serialize + Deserialize> {
    item: Vec<T>,
}
#[derive(PartialEq, Debug, Serialize, Deserialize)]
#[allow(non_snake_case)]
struct DescribeVpcsResponse {
    requestId: String,
    vpcSet: Helper<VpcSet>,
}
```

**Comment by oli-obk** [comment]
Or maybe your idea works if you implement `Deserialize` for `Vec<T: YourTrait>` where `YourTrait` is implemented for all `VpcSet` and similar types.

**Comment by oli-obk** [comment]
@hugoduncan it works if you use a custom `ItemVec<T>` type:

```rust
    let s = r#"
    <?xml version="1.0" encoding="UTF-8"?>
    <DescribeVpcsResponse xmlns="http://ec2.amazonaws.com/doc/2014-10-01/">
        <requestId>8d521e9a-509e-4ef6-bbb7-9f1ac0d49cd1</requestId>
        <vpcSet>
            <item>
                <vpcId>vpc-ba0d18d8</vpcId>
                <state>available</state>
            </item>
        </vpcSet>
    </DescribeVpcsResponse>"#;
    #[derive(PartialEq, Debug, Serialize, Deserialize)]
    #[allow(non_snake_case)]
    struct VpcSet {
        vpcId: String,
        state: String,
    }

    #[derive(PartialEq, Debug, Serialize)]
    struct ItemVec<T: de::Deserialize>(Vec<T>);

    impl<T: de::Deserialize> de::Deserialize for ItemVec<T> {
        fn deserialize<D>(deserializer: &mut D) -> Result<ItemVec<T>, D::Error>
            where D: de::Deserializer,
        {
            #[derive(PartialEq, Debug, Serialize, Deserialize)]
            struct Helper<U> {
                item: Vec<U>,
            }
            let h: Helper<_> = try!(de::Deserialize::deserialize(deserializer));
            Ok(ItemVec(h.item))
        }
    }
    #[derive(PartialEq, Debug, Serialize, Deserialize)]
    #[allow(non_snake_case)]
    struct DescribeVpcsResponse {
        requestId: String,
        vpcSet: ItemVec<VpcSet>,
    }
    test_parse_ok(&[
        (
            s,
            DescribeVpcsResponse {
                requestId: "8d521e9a-509e-4ef6-bbb7-9f1ac0d49cd1".to_string(),
                vpcSet: ItemVec(vec![ VpcSet {
                    vpcId: "vpc-ba0d18d8".to_string(),
                    state: "available".to_string(),
                }]),
            },
        ),
    ]);
```

**Comment by oli-obk** [comment]
together with some `Deref` and `DerefMut` implementations this should be almost as using a `Vec` directly

**Comment by hugoduncan** [comment]
@oli-obk Thanks for the example code.  Using a custom `Deserialize` implementation on a newtype for `Vec` does indeed seem to be a workable approach.

**Comment by nicolai86** [comment]
Using the latest rust nightly the XML fork still does not compile:

```
src/main.rs:41:21: 41:41 error: the trait `serde::de::Deserialize` is not implemented for the type `gesmes` [E0277]
src/main.rs:41     let a: gesmes = serde::xml::from_str(s).unwrap();
```

given this simple example: 

```
#![feature(plugin)]
#![feature(custom_derive, plugin)]
#[plugin(serde_macros)]

extern crate serde;
use serde::xml;

#[derive(PartialEq, Serialize, Deserialize)]
#[allow(non_snake_case)]
struct gesmes {
    subject: String,
}

fn main() {
    let s = r#"
        <?xml version="1.0" encoding="UTF-8"?>
        <gesmes:Envelope xmlns:gesmes="http://www.gesmes.org/xml/2002-08-01" xmlns="http://www.ecb.int/vocabulary/2002-08-01/eurofxref">
            <gesmes:subject>Reference rates</gesmes:subject>
        </gesmes:Envelope>"#;

    let a: gesmes = serde::xml::from_str(s).unwrap();
    println!("Hello, world!\n{}", a.subject);
}
```

@oli-obk is this in any case related to #49 ?

I'm currently running `rustc 1.0.0-nightly (abf0548b5 2015-04-15) (built 2015-04-15)`…

**Comment by oli-obk** [comment]
I think you need to `use serde::de::Deserialize`. Maybe report a bug?

**Comment by oli-obk** [comment]
@nicolai86 also, I have not implemented namespacing... But even if it were implemented, your struct's name should be `Envelope`. I'm not sure how to even handle namespaces... maybe I could just ignore them all?

**Comment by nicolai86** [comment]
I think ignoring the namespaces is a good enough solution for now.

Will adjust the code for a Deserializer and write a ticket for the serialize impl later.. Thanks!

**Comment by oli-obk** [comment]
namespaces are ignored now.

**Comment by hugoduncan** [comment]
It would be useful if all the internal logging output could be put behind a macro/feature that defaulted to no output.

**Comment by nicolai86** [comment]
for what it's worth my error was a missing dependency - `serde_macros`, along with the line `#![plugin(serde_macros)]`

Serde-XML now compiles, which leads to my next question: do I have to define the complete XML structure? Because I'm not interested in the entire XMLs content, only in bits, which results in
`UnknownField` returns for the not defined nodes.

Thanks for the great help so far!

**Comment by nicolai86** [comment]
Regarding the XML whitespace handling, see https://gist.github.com/nicolai86/33472bfc7b546521c9a6 for an example that panics.

The problem is the whitespace between `<Cube> </Cube>`. Removing it makes it pass.

**Comment by nicolai86** [comment]
As a last note, directly closed XML nodes like `<Cube currency='GBP' rate='0.81725'/>` panic, while `<Cube currency='GBP' rate='0.81725'></Cube>` work.

@oli-obk I'm not yet fluent enough with rust to write failing example specs, but would it help if I tried to provide them as a PR to your repo?

**Comment by oli-obk** [comment]
> @oli-obk I'm not yet fluent enough with rust to write failing example specs, but would it help if I tried to provide them as a PR to your repo?

it's perfectly fine to post them here, but I also need the rust-struct definition.

But feel free to post PRs if you want.

**Comment by oli-obk** [comment]
>The problem is the whitespace between <Cube> </Cube>. Removing it makes it pass.

That's a tradeoff that I'm not sure about. How would you parse an xml like this: `<a number="42">cake</a>`?
Right now it is:

```rust
struct a {
    number: i32,
    #[serde(rename="$value")]
    the_inner_value: String,
}
```

But this will also require me to parse `<a number="42">   </a>` to fill `the_inner_value` with three spaces. I could always trim the spaces and not parse to `$value` if the inner string is empty. I'm not sure how to proceed from here...

What could work is if I could "offer" optional struct fields or got a list of all legal struct fields. I'll post an issue and ask @erickt

**Comment by oli-obk** [comment]
oh well... or it's actually not that hard and I was just running in circles. Whitespace should not be an issue anymore, but inner text can still be parsed *yay*

**Comment by nicolai86** [comment]
@oli-obk I can confirm that this works properly now. Regarding the structs for the directly closed XML nodes:

```
#[derive(PartialEq, Serialize, Deserialize)]
#[allow(non_snake_case)]
struct TheSender {
    name: String,
}

#[derive(PartialEq, Serialize, Deserialize)]
#[allow(non_snake_case)]
struct CurrencyCube {
    currency: String,
    rate: f32,
}

#[derive(PartialEq, Serialize, Deserialize)]
#[allow(non_snake_case)]
struct DateCube {
    Cube: Vec<CurrencyCube>,
    time: String,
}

#[derive(PartialEq, Serialize, Deserialize)]
#[allow(non_snake_case)]
struct OuterCube {
    Cube: Vec<DateCube>,
}

#[derive(PartialEq, Serialize, Deserialize)]
#[allow(non_snake_case)]
struct Envelope {
    subject: String,
    Sender:  TheSender,
    Cube:    OuterCube,
}
```

That should parse the following XML, but returns an error instead:

```
let s = r#"
        <?xml version="1.0" encoding="UTF-8"?>
        <gesmes:Envelope xmlns:gesmes="http://www.gesmes.org/xml/2002-08-01" xmlns="http://www.ecb.int/vocabulary/2002-08-01/eurofxref">
            <gesmes:subject>Reference rates</gesmes:subject>
            <gesmes:Sender>
                <gesmes:name>European Central Bank</gesmes:name>
            </gesmes:Sender>
            <Cube>
                <Cube time='2014-05-09'>
                    <Cube currency='USD' rate='1.3781'/>
                    <Cube currency='GBP' rate='0.81725'/>
                </Cube>
            </Cube>
        </gesmes:Envelope>"#;
```

Notice the `<Cube currency='GBP' rate='0.81725'/>`

This errors: 
```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: SyntaxError(expected end tag, 10, 57)',
```

**Comment by oli-obk** [comment]
on it right now, it was unimplemented xD bad error for unimplemented stuff though... gimme a few minutes

**Comment by oli-obk** [comment]
there ya go

**Comment by nicolai86** [comment]
@oli-obk I have two relativly unrelated questions:
- how complicated whould it be to allow structs to only extract parts of the given XML document? e.g. ignoring attributes or nodes entirely (see `UnknownField("XXX")`).
- whould it be possible to define macros that allow for deeper attribute extraction, e.g. like go allows with tags:

```go
type Envelop struct {
	Subject string `xml:"subject"`
	Sender  string `xml:"Sender>name"`
}
```

which could roughly look like this in rust:

``` rust
#[derive(PartialEq, Serialize, Deserialize)]
#[allow(non_snake_case)]
struct Envelope {
    subject: String,
    #[serde(extract="Sender/name")]
    Sender:  TheSender,
    Cube:    OuterCube,
}
```

Thanks again!

**Comment by nicolai86** [comment]
@oli-obk  the current commit errors on compilation:

```
lexer.rs:156:29: 156:43 error: variable `FirstAttribute` from pattern #2 is not bound in pattern #1
lexer.rs:156             AttributeName | FirstAttribute => self.decode_attr_name(),
```

**Comment by oli-obk** [comment]
>whould it be possible to define macros that allow for deeper attribute extraction, e.g. like go allows with tags:

this is what @hugoduncan was also asking about. I'll look into it. But adding stuff just for xml might be overkill...

**Comment by oli-obk** [comment]
> @oli-obk the current commit errors on compilation

that's odd, works here :/

**Comment by oli-obk** [comment]
now it works ^^

**Comment by nicolai86** [comment]
@oli-obk thanks alot ! works like a charm now :+1: can't wait for this to get merged into master.

**Comment by oli-obk** [comment]
> how complicated whould it be to allow structs to only extract parts of the given XML document? e.g. ignoring attributes or nodes entirely (see UnknownField("XXX"))

That's someting that could be done in serde in general, it's not xml specific. Please post a bug/feature request describing it in terms of json, as that is in master.

**Comment by nicolai86** [comment]
I've just opened #60 to keep that issue in mind.

**Comment by erickt** [comment]
@oli-obk: Would you like to land this in a https://github.com/serde-rs repo?

**Comment by oli-obk** [comment]
@erickt sounds like a plan. a separate crate should speed up compilation quite a bit.

**Comment by oli-obk** [comment]
closed in favor of https://github.com/oli-obk/serde-xml

**Pull request closed without merging**
