### PR TITLE
Disallow variant field names to conflict with tag of internally-tagged enum

### PR DESCRIPTION
**Pull request by H2CO3**
Fixes https://github.com/serde-rs/serde/issues/1161.

### CODE REVIEW

**Comment by oli-obk** [comment]
Could you add a test for it?

**Comment by H2CO3** [comment]
Sure thing! Where do I add one? I'm afraid I don't completely understand the structure of the `serde_tests` crate, is that the one I need? Thanks.

**Comment by H2CO3** [comment]
@oli-obk Hey, could you help me with adding tests? I can't even run the test suite. I have latest nightly, but when I run 

    cargo +nightly test --features="unstable"

then basically every compile-time test fails, with errors such as

    error: tests/compile-fail/remote/wrong_de.rs:10: unexpected error: '10:1: 10:27: can't find crate for `serde_derive` [E0463]'

and

    found crate `serde_derive` compiled by an incompatible version of rustc [E0514]

What am I missing?

**Comment by oli-obk** [comment]
That's an unfortunate side effect of `compiletest-rs`. You need to run `cargo clean` or even `rustup override set nightly` instead of `cargo +nighty`

**Comment by H2CO3** [comment]
I've already tried cleaning; in fact, I've deleted and re-`git clone`'d the entire repository, without success :( `rustup override set stable` doesn't seem to have helped either, I still get the very same errors.

Just to be clear: I've set up my cargo config so that all `serde`-related dependencies are searched for locally. Cargo build reports:

    Compiling serde v1.0.27 (file:///Users/H2CO3/Projects/serde/serde)
    Compiling serde_derive_internals v0.19.0 (file:///Users/H2CO3/Projects/serde/serde_derive_internals)
    Compiling serde_derive v1.0.27 (file:///Users/H2CO3/Projects/serde/serde_derive)
    Compiling serde_test v1.0.27 (file:///Users/H2CO3/Projects/serde/serde_test)
    Compiling serde_test_suite v0.0.0 (file:///Users/H2CO3/Projects/serde/test_suite)

Am I correct that this is what should be done?

**Comment by H2CO3** [comment]
@dtolnay hey there! Thanks for the tests and the guidance. I'm glad you found this useful. 👍

**Pull request merged**
