### PR TITLE
Unify 'skip_serialization_if_empty' and 'skip_serialization_if_none' via trait

### PR DESCRIPTION
**Pull request by target-san**
It seems I accidentally closed #208 by moving everything to separate branch

### CODE REVIEW

**Comment by target-san** [comment]
We cannot cover standard collections with Empty trait. HashMap cannot be extended with custom traits on stable, because its third generic arg is unstable both in its bound and default.

**Comment by oli-obk** [comment]
You don't need to specify the third arg, you can just leave it at its default:

```rust
use std::collections::HashMap;
use std::hash::Hash;

trait Dummy {
    fn is_cake(&self) -> bool;
}

impl<K: Eq + Hash, V> Dummy for HashMap<K, V> {
    fn is_cake(&self) -> bool { self.is_empty() }
}

fn main() {
}
```

**Comment by target-san** [comment]
Thanks, didn't know this

**Comment by target-san** [comment]
I've stumbled upon pretty stupid problem when implementing explicit trait Empty.
The problem is, `::serde::ser::empty::Empty::is_empty($value_type)` can support only either reference field or value field. But not both. Because `::serde::ser::empty::Empty::is_empty(&$value_type)` tries to pass &&-refernce when supplied &-reference. Using ` $value_type as Empty` also doesn't do any good, for the same reason. I guess our only option is to use duck-typing.

**Comment by erickt** [comment]
This was alternatively implemented in #238. Thanks though!

**Pull request closed without merging**
