### PR TITLE
Update for latest libsyntax changes

### PR DESCRIPTION
**Pull request by antrik**
This one is mostly about updating dependencies on syntex, aster, and quasi -- along with a small code patch for adapting to the actual interface changes.

### CODE REVIEW

**Comment by antrik** [comment]
And finally, this one depends on https://github.com/serde-rs/aster/pull/78 , https://github.com/serde-rs/syntex/pull/44 , as well as https://github.com/serde-rs/quasi/pull/41

**Comment by KodrAus** [comment]
Does this build now?

**Comment by dtolnay** [comment]
@oli-obk @erickt does one of you have permission to retrigger the Travis build?

**Comment by erickt** [comment]
@dtolnay: I've merged this in. Hopefully it'll pass travis now.

**Comment by dtolnay** [comment]
Looks like it passed! Let's cut a release to unblock everybody.

**Comment by erickt** [comment]
@dtolnay: 0.7.4 has (finally) been released! Thanks so much for all your work getting this out.

**Pull request merged**
