### PR TITLE
Clamp hints coming from untrusted input to 4096

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by oli-obk** [comment]
what's the advantage of this? The user can still supply a huge number of elements

**Comment by nox** [comment]
https://github.com/serde-rs/serde/issues/744

**Comment by oli-obk** [comment]
This is a good protection against simple attacks with small payload

**Comment by oli-obk** [comment]
please also adjust all the seq_impl! calls: https://github.com/serde-rs/serde/blob/090c8a7049cff6cd98139a8fcfc28b65ef73ec2d/serde/src/de/impls.rs#L439

**Pull request merged**
