### PR TITLE
Generate bounds on type parameters only

### LINKED ISSUE #435: Generated code triggers private_in_public future compatibility warnings.
If a private field of a public type contains a private type, the generated bounds result in warnings such as (example from Servo):
```rust
<quote expansion>:1:12: 1:22 warning: private type in public interface, #[warn(private_in_public)] on by default
<quote expansion>:1  where Vec<GlyphEntry>: _serde::ser::Serialize,
                               ^~~~~~~~~~
<quote expansion>:1:12: 1:22 warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
<quote expansion>:1:12: 1:22 note: for more information, see the explanation for E0446 (`--explain E0446`)
```

See https://github.com/rust-lang/rfcs/pull/1671#issuecomment-231555393 for more on the possible future of private types in bounds (i.e. no action may be necessary in the future if that RFC gets through).

### LINKED ISSUE #436: Only emit bounds that contain type parameters
Currently we generate something like:

```rust
struct S {
    i: i32,
}

impl Serialize for S where i32: Serialize { /* ... */ }
```

### LINKED ISSUE #441: overflow evaluating the requirement `test_ser::Outer: test_annotations::serde::Serialize`
I have noticed an issue in one of my projects, that I have been able to reduce to the following example:

```rust
#[derive(Serialize)]
struct Outer {
    inner: Box<Option<Inner>>
}

#[derive(Serialize)]
struct Inner {
    outer: Outer
}
```

This fails to compile with: 

```
/Users/ben/oss/serde/testing/target/debug/build/serde_testing-5d7d99abec542b6e/out/test.rs:16645:18: 16645:40 error: overflow evaluating the requirement `test_ser::Outer: test_annotations::serde::Serialize` [E0275]
/Users/ben/oss/serde/testing/target/debug/build/serde_testing-5d7d99abec542b6e/out/test.rs:16645             impl _serde::ser::Serialize for Outer where
                                                                                                                  ^~~~~~~~~~~~~~~~~~~~~~
tests/test.rs:4:1: 4:48 note: in this expansion of include!
/Users/ben/oss/serde/testing/target/debug/build/serde_testing-5d7d99abec542b6e/out/test.rs:16645:18: 16645:40 help: run `rustc --explain E0275` to see a detailed explanation
/Users/ben/oss/serde/testing/target/debug/build/serde_testing-5d7d99abec542b6e/out/test.rs:16645:18: 16645:40 note: required by `test_annotations::serde::Serialize`
error: aborting due to previous error
error: Could not compile `serde_testing`.

To learn more, run the command again with --verbose.
```

These examples compiled in 0.7.11 and earlier, but has failed in 0.7.12 and all versions since.

### LINKED ISSUE #443: derive(Serialize) regression with lifetimes
This used to work around version `0.7.10` of serde_codegen...

```rust
#[derive(Serialize)]
struct S<'a> {
	a: Option<&'static str>,
	b: Option<&'a str>,
}
```

```
error: mismatched types [E0308]
#[derive(Serialize)]
help: run `rustc --explain E0308` to see a detailed explanation
note: expected type `serde::Serialize`
note:    found type `serde::Serialize`
note: the lifetime 'a as defined on the impl at 31:9...
#[derive(Serialize)]
note: ...does not necessarily outlive the static lifetime
```

### PR DESCRIPTION
**Pull request by dtolnay**
Fixes #435 and fixes #436 and fixes #441 and fixes #443.

### CODE REVIEW

**Comment by dtolnay** [comment]
```rust
#[derive(Serialize)]
struct S<'a, A: 'a, B, C> {
    a: Option<&'a A>,
    b: B,
    #[serde(skip_serializing)]
    c: C,
    i: i32,
}
```

Before:

```rust
impl<'a, A: 'a, B, C> Serialize for S<'a, A, B, C>
    where Option<&'a A>: Serialize,
          B: Serialize,
          i32: Serialize { /* ... */ }
```

After:

```rust
impl<'a, A: 'a, B, C> Serialize for S<'a, A, B, C>
    where A: Serialize,
          B: Serialize { /* ... */ }
```

**Comment by dtolnay** [comment]
Hmm I have to figure out how to make the hygiene work on nightly.

**Comment by dtolnay** [comment]
I am done working on this for today. @oli-obk see if you can figure out a way that works with serde_macros.

**Comment by oli-obk** [comment]
we have some pretty funky spans:

> tests/../../testing/tests/test_gen.rs:42:19: 1:1 error: the trait bound `T: serde::Serialize` is not satisfied [E0277]

**Comment by dtolnay** [comment]
Yet serde_codegen is fine with it. I think serde_macros is seeing two different `T`s, one in the bound and a different one in the field type.

**Comment by oli-obk** [comment]
It must be more complex... If I compile `test_gen.rs` directly, it works fine, if I do it through the `test.rs.in`, everything goes haywire.

**Comment by oli-obk** [comment]
fun fact: `include!` is the "culprit". If i do the following, the tests run through fine:

```rust
#[macro_use]
#[path = "../../testing/tests/macros.rs"]
mod macros;

#[path = "../../testing/tests/test_annotations.rs"]
mod test_annotations;
#[path = "../../testing/tests/test_bytes.rs"]
mod test_bytes;
#[path = "../../testing/tests/test_de.rs"]
mod test_de;
#[path = "../../testing/tests/test_gen.rs"]
mod test_gen;
#[path = "../../testing/tests/test_macros.rs"]
mod test_macros;
#[path = "../../testing/tests/test_ser.rs"]
mod test_ser;
```

**Comment by oli-obk** [comment]
pretty=expanded code of `include!` version:

```rust
#[automatically_derived]
        impl <T> _serde::ser::Serialize for With<T> {
            fn serialize<__S>(&self, _serializer: &mut __S)
             -> ::std::result::Result<(), __S::Error> where
             __S: _serde::ser::Serializer {
                {
                    let mut state =
                        match _serializer.serialize_struct("With", 0 + 1) {
                            ::std::result::Result::Ok(val) => val,
                            ::std::result::Result::Err(err) => {
                                return ::std::result::Result::Err(::std::convert::From::from(err))
                            }
                        };
                    if !false {
                        match _serializer.serialize_struct_elt(&mut state,
                                                               "t", &self.t) {
                            ::std::result::Result::Ok(val) => val,
                            ::std::result::Result::Err(err) => {
                                return ::std::result::Result::Err(::std::convert::From::from(err))
                            }
                        };
                    }
                    _serializer.serialize_struct_end(state)
                }
            }
        }
```

obviously the bound is missing. If I use `mod ...` instead of `include!` I get the correct code:

```rust
#[automatically_derived]
            impl <T> _serde::ser::Serialize for With<T> where
             T: _serde::ser::Serialize {
                fn serialize<__S>(&self, _serializer: &mut __S)
                 -> ::std::result::Result<(), __S::Error> where
                 __S: _serde::ser::Serializer {
                    {
                        let mut state =
                            match _serializer.serialize_struct("With", 0 + 1)
                                {
                                ::std::result::Result::Ok(val) => val,
                                ::std::result::Result::Err(err) => {
                                    return ::std::result::Result::Err(::std::convert::From::from(err))
                                }
                            };
                        if !false {
                            match _serializer.serialize_struct_elt(&mut state,
                                                                   "t",
                                                                   &self.t) {
                                ::std::result::Result::Ok(val) => val,
                                ::std::result::Result::Err(err) => {
                                    return ::std::result::Result::Err(::std::convert::From::from(err))
                                }
                            };
                        }
                        _serializer.serialize_struct_end(state)
                    }
                }
            }
```

**Comment by dtolnay** [comment]
Thanks for the fix :smiley:. I did not think the solution would be less hygiene instead of more hygiene.

**Comment by eddyb** [comment]
@dtolnay I expected `Option<&'a A>: Serialize`, not `A: Serialize`, TBQH. That is, bounds are kept if they refer to type parameters, instead of just putting bounds on type parameters.

**Comment by dtolnay** [comment]
That breaks this case:

```rust
#[derive(Serialize, Deserialize)]
struct RecursiveGenericA<T> {
    t: T,
    b: Box<RecursiveGenericB<T>>,
}

#[derive(Serialize, Deserialize)]
enum RecursiveGenericB<T> {
    T(T),
    A(RecursiveGenericA<T>),
}
```

**Comment by eddyb** [comment]
@dtolnay Ah, right. We can't have nice things :disappointed:.

**Comment by dtolnay** [comment]
One thing I still want to do is add a hardcoded exception for PhantomData. The following should not put a bound on T:

```rust
struct S<T> {
    phantom: PhantomData<T>
}
```

**Comment by dtolnay** [comment]
@eddyb oh it would also break this case:

```rust
#[derive(Serialize)]
struct S<'a> {
    a: Option<&'static str>,
    b: Option<&'a str>,
}
```

See #443.

**Pull request merged**
