### PR TITLE
Inform serializers about skipped fields.

### LINKED ISSUE #960: Pass field index to SerializeStruct::serialize_field
Similar to how `Serializer::serialize_*_variant` receives both the index and name of the variant. This would enable CBOR to deserialize correctly from a packed representation (integer keys) with fields that are conditionally skipped - https://github.com/pyfisch/cbor/issues/37.

### PR DESCRIPTION
**Pull request by sfackler**
Closes #960.

### CODE REVIEW

**Comment by dtolnay** [comment]
I would like to see a cbor PR working with this before I would merge it. I am on board with this idea but it would be tough to undo later if it turns out we are missing something...

Have you looked into how this interacts with unconditionally skipped fields?

```rust
#[derive(Serialize, Deserialize)]
struct Sfackler {
    a: u8,
    #[serde(skip)]
    b: u8,
    c: u8,
}
```

It looks like Serialize will call serialize_field("a"), skip_field("b"), serialize_field("c") so presumably "c" would be serialized with index 2, but then Deserialize invokes deserialize_struct("Sfackler", &["a", "c"]) in which there is no field with index 2.

**Comment by sfackler** [comment]
Yeah, the behavior for unconditionally skipped fields is wrong.

I'm not sure this is sufficient to handle compact struct field names - we'd also need to support numeric deserialization of field identifiers.

**Comment by dtolnay** [comment]
We used to have numeric deserialization of field identifiers but got rid of it because nobody ever used it. I would be okay putting it back.

**Comment by sfackler** [comment]
I've fixed the handling of skipped fields and enabled identifier deserialization from u32.

Here's an example of use for CBOR packed serialization: https://github.com/sfackler/cbor/commit/d2409da8166866f514eec26b0dbcf1ce7631e777

**Comment by dtolnay** [comment]
Thanks for persisting with this :heart:. I will try to squeeze in some of the other reviews tonight and get this released no later than tomorrow night.

**Comment by sfackler** [comment]
Thanks!

**Pull request merged**
