### PR TITLE
Mention Empty Field Bounds for Recursion

### PR DESCRIPTION
**Pull request by killercup**
Please excuse my stupidity. This corrects #451

### CODE REVIEW

**Comment by dtolnay** [comment]
I would rather explain why this sometimes works rather than simply saying to set it to `""`, because that is not a magic bullet for recursion and will not work in many cases.

**Comment by dtolnay** [comment]
Also it will be made unnecessary sometime in the next few days for 0.8.0 once I fix #436.

**Comment by dtolnay** [comment]
Closing because this is no longer necessary as of #456. I will revert the other commit.

**Comment by killercup** [comment]
Thanks, @dtolnay! :)

**Pull request closed without merging**
