### PR TITLE
Add `default_expr` and `default_fn`

### LINKED ISSUE #368: Support default literals
```rust
#[serde(default="0.1")]
pub n: f32
```

There is an ambiguity when the field is of function type so we need to figure that out.

### PR DESCRIPTION
**Pull request by bossmc**
A proposal to resolve #368, this adds `default_fn = ` as an alias for `default = ` and also adds `default_expr = ` to allow providing any valid expression (e.g, a single literal, or a custom function call, or even a block) which will be used as the generator for the default value when deserialising.

If `proc_macro_diagnostic` were stabilised, serde could emit a `deprecated` warning for use of `default = `, but, as it's not, I've just left both available.

### CODE REVIEW

**Comment by est31** [comment]
@dtolnay any news on this? I (and many others) would love to have the feature!

**Comment by jhpratt** [comment]
@dtolnay Any plans to merge this? It's a much desired feature.

**Comment by est31** [comment]
@dtolnay Is there sense for @bossmc to rebase this? As in: do you intend to merge this PR one day? What would you think about a fork of serde_derive having extensions like this one?

**Comment by dtolnay** [comment]
I'll close this for now, but anyone should feel free to make follow-up PRs as outlined in https://github.com/serde-rs/serde/pull/1490#pullrequestreview-288464564.

**Pull request closed without merging**
