### PR TITLE
Rustup too rustc 1.11.0-nightly (7746a334d 2016-05-28)

### PR DESCRIPTION
**Pull request by Manishearth**
cc @erickt

### CODE REVIEW

**Comment by Manishearth** [comment]
Okay, I'm not familiar enough with aster traits to fix this

**Comment by Manishearth** [comment]
Blocked on a publish of https://github.com/serde-rs/quasi/pull/42

**Comment by erickt** [comment]
@homu: r+ 379c9e7

**Comment by alexcrichton** [comment]
Changes like this which update syntex, a public dependency of serde_codegen (e.g. it reexports types from syntex) are actually a breaking change for the serde crate. Could this be signaled with a major version update or holding off the upgrade? This unfortunately breaks any other crate which is depending on serde_codegen as it may get a mismatch of syntex versions otherwise.

**Pull request merged**
