### PR TITLE
Use serde_codegen::expand in serde_tests/build.rs

### PR DESCRIPTION
**Pull request by dtolnay**

### CODE REVIEW

**Comment by dtolnay** [comment]
Blocked on https://github.com/serde-rs/aster/pull/84.

**Comment by erickt** [comment]
/me waves at @dtolnay :) just another one of those days, eh? two libsyntax breaks in just a few days. That hasn't happened in a while...

**Comment by dtolnay** [comment]
I rebased to pick up #372 and #373.

**Comment by erickt** [comment]
@homu: r+ 021f4f2d70c6af4ab5eefb813723ded8cbbc1c7c

**Pull request merged**
