### PR TITLE
Add changelog

### LINKED ISSUE #306: Add a changelog
It would be very helpful if the project included a changelog document, or if the releases on the releases page were given release notes. Right now there isn't an easy way to tell what has changed in each version of serde (and related crates.)

### PR DESCRIPTION
**Pull request by dtolnay**
Fixes #306.

[Rendered](https://github.com/dtolnay/serde/blob/changelog/CHANGELOG.md)

### CODE REVIEW

**Comment by oli-obk** [comment]
what's the advantage of a textual changelog over https://github.com/serde-rs/serde/releases ?

**Comment by dtolnay** [comment]
I had a somewhat negative experience with the Releases page yesterday. They are sorted by date tagged instead of date committed so we get 0.6.13 -> 0.6.14 -> 0.6.15-> 0.6.12 -> 0.6.11. Change history is not tracked in git, unlike for the wiki. We cannot accept PRs that modify the release notes.

I agree that we do not need to have both. We could have the releases page link to the changelog file.

**Comment by oli-obk** [comment]
Well... ususally we don't get a wrong ordering. Also it makes total sense to sort by date tagged, so if there are bugfix releases, these are given by the date they were created, not in order of release numbers.

Can't we backdate tags manually?

**Comment by dtolnay** [comment]
Good call. I will look into backdating the tags when I am back home next week.

**Comment by dtolnay** [comment]
I backdated the 0.6.13, 0.6.14, 0.6.15 tags to fix the ordering.

**Pull request closed without merging**
