### PR TITLE
Optimize few string allocations

### PR DESCRIPTION
**Pull request by klensy**
Few string allocating optimizations and replacing of deprecated `trim_left_matches`.

### CODE REVIEW

**Comment by klensy** [comment]
This ready to review, i guess ;-)

**Comment by klensy** [comment]
One month ping, @dtolnay.

**Review by dtolnay — COMMENTED** [review]
I probably am not going to review this. My projects get more PRs per month than can be reviewed, so I focus on the most impactful ones, and in this case from a skim I would expect zero effect on macro expansion performance. Allocators are fast and nothing here is a bottleneck part of the macro. That puts it right to the bottom for impactfulness unless there is some benchmark data to back it up.

You're free to leave it open if you want but please do not ping me.

**Comment by striezel** [comment]
> I probably am not going to review this. My projects get more PRs per month than can be reviewed, so I focus on the most impactful ones, [...]

That is completely understandable. Focus is important when time is a very limited resource.

Maybe one of your co-maintainers can afford the time to review this? I'd rather see pull requests reviewed late than not reviewed at all, because otherwise one may miss potential improvements, even if they are small.

@klensy:
>  Allocators are fast and nothing here is a bottleneck part of the macro. That puts it right to the bottom for impactfulness unless there is some benchmark data to back it up.

Did you run any benchmarks before and after the changes of this PR? If so, you could provide the data and then maybe it's easier for the maintainer(s) to make a decision on the possible impact of this PR.

**Review by dtolnay — COMMENTED** [review]
Skimming this PR again, everything touched here is in cold code that runs at most once or a low number of times per serde macro call. I don't see any way that compile performance could be sensitive to a few allocations in this part of the code. I think the original code is all right as is.

Thanks anyway for the PR!

**Pull request closed without merging**
