### PR TITLE
Add methods to provide field indices

### LINKED ISSUE #960: Pass field index to SerializeStruct::serialize_field
Similar to how `Serializer::serialize_*_variant` receives both the index and name of the variant. This would enable CBOR to deserialize correctly from a packed representation (integer keys) with fields that are conditionally skipped - https://github.com/pyfisch/cbor/issues/37.

### PR DESCRIPTION
**Pull request by sfackler**
Closes #960

This change does mean that if you run a new serde_derive with an old serde the build will fail. That seems like an uncommon situation to be stuck in though.

### CODE REVIEW

**Comment by sfackler** [comment]
I'd like to update serde_test's `Token` to be able to store the index, but I'm not sure what the back compat situation is there.

**Comment by dtolnay** [comment]
Are there any restrictions that need to be placed on how this is used? In particular, is the following valid and how would Bincode be expected to behave in this case?

```rust
rgb.serialize_indexed_field("g", 1, &self.g)?;
rgb.serialize_indexed_field("r", 0, &self.r)?;
rgb.serialize_indexed_field("b", 2, &self.b)?;
```

**Comment by dtolnay** [comment]
https://github.com/serde-rs/serde/issues/960#issuecomment-317225162 proposes a different approach.

**Comment by sfackler** [comment]
Closing in favor of #1022.

**Pull request closed without merging**
