### PR TITLE
Implement `Serialize`/`Deserialize` for `Range`

### PR DESCRIPTION
**Pull request by rocallahan**
I'm not sure whether we really need to be able to deserialize from an array, but `Duration` supports that so I followed suit.

### CODE REVIEW

**Comment by dtolnay** [comment]
Thanks! Deserializing from an array is used in Bincode and some other super compact formats - having them imitate a map where we deserialize a fake key and match on it would be slow.

**Comment by rocallahan** [comment]
There was bustage on "nightly". I just pushed an updated branch but you already merged...

**Comment by rocallahan** [comment]
I'll file a new PR with the fix.

**Comment by rocallahan** [comment]
Oh, you already fixed it. Great, thanks!

**Comment by dtolnay** [comment]
Would you be able to help me with the RangeInclusive impls? We do the silly thing now where we serialize every value in the range.

It may make sense to work more like:

```rust
#[derive(Serialize, Deserialize)]
pub enum RangeInclusive<Idx> {
    Empty {
        at: Idx,
    },
    NonEmpty {
        start: Idx,
        end: Idx,
    },
}
```

Or possibly a friendlier representation if you can come up with one.

```rust
#[derive(Serialize, Deserialize)]
pub struct RangeInclusive<Idx> {
    start: Idx,
    end: Option<Idx>,
}
```

**Pull request merged**
