### PR TITLE
Fix nightly check in serde-syntex-example

### LINKED ISSUE #361: Serde-syntex-example does not compile with plugin
```
$ cargo run --features nightly --no-default-features
   Compiling serde-syntex-example v0.1.0 (file:///github/serde/examples/serde-syntex-example)
src/main.rs.in:1:21: 1:32 error: `#[derive]` for custom traits is not stable enough for use and is subject to change (see issue #29644)
src/main.rs.in:1 #[derive(Serialize, Deserialize, Debug)]
                                     ^~~~~~~~~~~
src/main.rs:8:1: 8:24 note: in this expansion of include!
src/main.rs.in:1:21: 1:32 help: add #![feature(custom_derive)] to the crate attributes to enable
src/main.rs.in:1:10: 1:19 error: `#[derive]` for custom traits is not stable enough for use and is subject to change (see issue #29644)
src/main.rs.in:1 #[derive(Serialize, Deserialize, Debug)]
                          ^~~~~~~~~
src/main.rs:8:1: 8:24 note: in this expansion of include!
src/main.rs.in:1:10: 1:19 help: add #![feature(custom_derive)] to the crate attributes to enable
error: aborting due to 2 previous errors
error: Could not compile `serde-syntex-example`.

To learn more, run the command again with --verbose.
```

### PR DESCRIPTION
**Pull request by dtolnay**
Fixes #361.

### CODE REVIEW

**Comment by dtolnay** [comment]
This matches the check in [build.rs](https://github.com/serde-rs/serde/blob/58fa30200708cd1ccc91d2bbea0b620f69b5397b/examples/serde-syntex-example/build.rs#L22).

**Comment by oli-obk** [comment]
Please add a `cargo run --features nightly --no-default-features` check to travis, so this is actually tested.

**Comment by dtolnay** [comment]
Good call - done.

**Comment by oli-obk** [comment]
@homu r+

**Comment by oli-obk** [comment]
1.5 doesn't have a stable libcore yet

**Comment by dtolnay** [comment]
I added `--skip 1.5.0` like we have for serde's `cargo build --no-default-features`.

**Comment by oli-obk** [comment]
@homu r+

**Pull request merged**
