### PR TITLE
fix(error): Report `UnknownVariant`

### PR DESCRIPTION
**Pull request by tomprogrammer**
Don't unify it with syntax errors.

### CODE REVIEW

**Comment by tomprogrammer** [comment]
I will update my PR on https://github.com/serde-rs/json/pull/11 if this one is merged.

**Comment by erickt** [comment]
Ooh nice catch before I cut the release :)

**Comment by erickt** [comment]
On serde_json, I've also got 0.7 almost merged in. Give me a moment to do that.

**Comment by tomprogrammer** [comment]
I just saw another method [`invalid_value`](https://github.com/serde-rs/serde/blob/master/serde/src/de/mod.rs#L27) on `de::Error` trait, maybe you want to forward it through `value::Error` also.

**Comment by erickt** [comment]
@tomprogrammer: I'll take care of it, and the travis build failure.

**Comment by tomprogrammer** [comment]
Meh, the failure is a typo...

Thanks!

**Comment by tomprogrammer** [comment]
Closing as mentioned in #249.

**Pull request closed without merging**
