### PR TITLE
Stop building on 1.5.0

### PR DESCRIPTION
**Pull request by dtolnay**
Syntex no longer supports this version of Rust.

### CODE REVIEW

**Comment by erickt** [comment]
We can drop 1.6.0 too now that 1.9.0 is out :)

**Comment by erickt** [comment]
Can you add explicit builders to build 1.7.0 and 1.8.0 as well?

**Comment by dtolnay** [comment]
Done.

**Comment by erickt** [comment]
@homu: r+ 7375b4e

**Pull request merged**
