### PR TITLE
Fix a panic when deriving `Deserialize` for an enum with tuple and struct with flatten field

### LINKED ISSUE #1904: Deserialize failed to derive on enums with tuple variant and flatten struct variant
[Instead of thousand of words](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f1ea8c90736214e52d74c4ca0cab973b)

This code is failed to compile due to panic in serde derive:
```rust
#[derive(Deserialize)]
enum Failed {
    Tuple(f64, String),
    Flatten {
        #[serde(flatten)]
        nested: Nested,
    },
}
```
Output:
```bash
   Compiling playground v0.0.1 (/playground)
error: proc-macro derive panicked
  --> src/lib.rs:30:10
   |
30 | #[derive(Deserialize)]
   |          ^^^^^^^^^^^
   |
   = help: message: assertion failed: !cattrs.has_flatten()

error: aborting due to previous error

error: could not compile `playground`.

To learn more, run the command again with --verbose.
```

Each variant individually and `Serialize` derive works well, problem is only in combination of tuple variant and struct variant, when struct variant contains flattened field.

### PR DESCRIPTION
**Pull request by Mingun**
Fixes #1904

### CODE REVIEW

**Comment by Mingun** [comment]
@dtolnay, I see that you've periodically commit something here. Please don't ignore any work from contributors. If you do not intend to accept it, just close the PR with the appropriate comment so as not to waste either your or our time.

@oli-obk, @erickt, maybe can somebody of you can look at this? Or anybody else have merge rights?

**Comment by oli-obk** [comment]
> I see that you've periodically commit something here. Please don't ignore any work from contributors. If you do not intend to accept it, just close the PR with the appropriate comment so as not to waste either your or our time.

That statement is very rude and honestly has the opposite effect of what you desired. Please be respectful of maintainer time. It is entirely reasonable to open a PR and wait multiple weeks until the maintainer has time for your PR. No maintainer has an obligation to do anything beyond their intrinsic motivation, comments like yours are not helpful for keeping intrinsic motivation up.

**Comment by Mingun** [comment]
> That statement is very rude

@oli-obk, my apologies if my ignorance of English struck you as rude. I do not see anything rude in stating the facts.

What you're saying would be forgivable if it was an isolated case, or PR was big, or for incomprehensible purposes. You can at least just leave a comment "sorry, there is no time." But keep quiet and do that regularly...

In the end, the community has [repeatedly](https://github.com/serde-rs/serde/issues/1025) [offered](https://github.com/serde-rs/serde/issues/1723) assistance in maintaining the project, but maintainers do not just lack time to do this -- they do not want someone else to do this. Like a dog in the manger, as they say. Ironically, your comment only confirms everything that is said here -- instead of looking at PR, you are beginning to speculate on what would be better to do. 

I see parallels in the current situation with what happened with io.js a few years ago. Fortunately, there the maintainers listened to the voice of the community. It remains hoped that this lesson has been learned.

**Comment by dtolnay** [comment]
Is there a particular person you feel has been doing a good job providing code reviews of serde PRs to the point of perhaps having earned merge permission? It definitely doesn't seem like it to me but I am still interested in your opinion @Mingun.

As far as my own time, it always gets prioritized according to what is most impactful, which currently happens to be my Wasm proc macros RFC a.k.a. make serde_derive compile in 0.0 seconds!

I can say "please do not periodically commit anything to serde unless *all* pull requests are being reviewed" is not a reasonable perspective. The latter is not a goal at the expense of dedicating time in more impactful ways.

**Comment by dtolnay** [comment]
> In the end, the community has [repeatedly](https://github.com/serde-rs/serde/issues/1025) [offered](https://github.com/serde-rs/serde/issues/1723) assistance in maintaining the project, but maintainers do not just lack time to do this -- they do not want someone else to do this

I went and reread both of the threads you linked fully, and it turns out there is not one single person in either of them offering to help in maintenance, so your framing on this is extremely disingenuous. The nearest thing is *you* @Mingun "volunteering" *other people* to do the work, which is..... not how this works. On top of this, framing the only developer willing to participate in the work as "dog in the manger" is not a productive contribution to the situation. I've set a 30-day ban for you over this but I would love for you to contribute productively after that point if you are still willing.

**Comment by Mingun** [comment]
It is very sad that instead of listening to criticism, you are scaling your ego. Your behavior looks especially low when you shut your opponent's mouth to confirm your point of view.

> there is not one single person in either of them offering to help in maintenance, so your framing on this is extremely disingenuous.

I believed that the initial steps of a third-party developer who wants to help the project were to do PRs and inquire about the status of the project. If the owners / maintainers recognize the difficulties and express a desire to get help, then you can already offer it. I have not seen such a desire.

The lack of information from official maintainers (unfortunately, besides you, it is not clear who this is, since GitHub does not provide this information and it is not written anywhere) that they need help, even if there are two issues, which indicated that something is not good in the current situation, I regard it as that it is not required by them. Whereas all issues / PRs are usually ignored, I do not understand the ways in which you even assume that someone would offer help, even if they could.

Besides, I do not see any disingenuous from my side if I correctly understand meaning of the "assistance" word (which, I think, you use as indicator to blame me in disingenuous). Making PRs fixing bugs is fall into the category of assistance, don't you think? Of course, it would be better, if I'd write "try to assist". Sorry for that, it is not so easely to me as non-native speaker to discuss on not technical themes, where I could have lack of some typical patterns. I do not consider this an excuse for the use of administrative levers.

> On top of this, framing the only developer willing to participate in the work as "dog in the manger" is not a productive contribution to the situation.

Right now I see 42 open PRs from 38 people what I can not call "the only developer willing to participate in the work". Ok, some of them opened several years ago, but at least 7 was opened this year (from 7 different people), so I would say, that here _has_ the active developers.

> I would love for you to contribute productively after that point if you are still willing.

I would be glad, but unfortunately it does not depend on me, as eloquently evidenced by the closed, but not merged status of this PR, which itself does not depend on our off-topic.

**Comment by zeenix** [comment]
> I went and reread both of the threads you linked fully, and it turns out there is not one single person in either of them offering to help in maintenance

As I [commented 2 years prior to your comment here](https://github.com/serde-rs/serde/issues/1723#issuecomment-740676835), this is a chicken&egg problem. You won't just give merge rights to the project to the first person who volunteers. So it has to be a contributor and if important PRs don't get merged or get even a review for years, how can someone step up for the job?

**Pull request closed without merging**
