### PR TITLE
Replace `try!` with `?` in serde_derive

### PR DESCRIPTION
**Pull request by dtolnay**
#2366

As of today, this regresses compile time of serde's generated code by 6.5–7.5% which is too bad. However `try!` has been disastrous for readability of the generated code coming out of `cargo expand`. I was expecting the performance problems in rustc to be fixed a long time ago but at this point it doesn't seem like that is going to happen.

### CODE REVIEW

**Comment by Mingun** [comment]
I see, that not all `try!` was replaced by `?`. I would say, most of them. Is it so conceived?

**Comment by Baptistemontan** [comment]
So what about https://github.com/serde-rs/serde/commit/91ec1c290f73777a49d200c880a3e87d86067a94 ? The crate itself should suffer from readability but it goes backward for generated code ?

**Comment by Mingun** [comment]
Yes, that is... very strange decision :)

**Comment by dtolnay** [comment]
It's specifically `cargo expand` readability that is the motivation.

People are not looking at `cargo expand` of the serde crate. They are looking at expanded derive macros.

**Pull request merged**
