### PR TITLE
Add test for expansion inside of cfg_attr

### PR DESCRIPTION
**Pull request by dtolnay**
Test for #148. Requires https://github.com/serde-rs/syntex/pull/71 + Syntex release.

### CODE REVIEW

**Comment by erickt** [comment]
r=me once serde-rs/syntex#71 lands.

**Comment by dtolnay** [comment]
I marked this WIP until we get a Syntex release to depend on. As far as I know nobody is waiting urgently for this so we can just wait for the next libsyntax break.

**Comment by erickt** [comment]
@homu: r+ 675caa8

**Comment by erickt** [comment]
@dtolnay: syntex is updated, but this is failing on stable and beta with things like:

```
/Users/erickt/projects/rust/serde/serde/serde_tests/target/debug/build/serde_tests-0dc644810d6621ba/out/test.rs:16260:9: 16260:22 error: the trait bound `test_macros::NamedUnit: std::cmp::PartialEq` is not satisfied [E0277]
/Users/erickt/projects/rust/serde/serde/serde_tests/target/debug/build/serde_tests-0dc644810d6621ba/out/test.rs:16260         assert_tokens(&NamedUnit, vec!(Token :: UnitStruct ( "NamedUnit" )));
```

Do you know what's up? Maybe the bug hasn't been fixed in syntex yet.

**Comment by dtolnay** [comment]
That's so strange. It works on the nightly compiler using Syntex, but not on the beta compiler using Syntex. What would be the difference between those?

The generated code looks correct in both cases:

```rust
#[cfg_attr(all(), derive(PartialEq, Debug))]
struct NamedUnit;
#[cfg(all())]
const _IMPL_DESERIALIZE_FOR_NamedUnit: () = { /* ... */ };
#[cfg(all())]
const _IMPL_SERIALIZE_FOR_NamedUnit: () = { /* ... */ };
```

**Comment by dtolnay** [comment]
Interesting, [`cargo expand`](https://github.com/dtolnay/cargo-expand) on beta shows `#[derive(PartialEq, Debug)]` but on nightly it shows them expanded. That must have something to do with it. Now to figure out why...

**Comment by dtolnay** [comment]
```rust
#[cfg_attr(all(), cfg_attr(all(), derive(Debug)))]
struct S;

fn main() {
    println!("{:?}", S);
}
```

This works on nightly but not stable/beta. [Playground link](https://play.rust-lang.org/?code=%23%5Bcfg_attr(all()%2C%20cfg_attr(all()%2C%20derive(Debug)))%5D%0Astruct%20S%3B%0A%0Afn%20main()%20%7B%0A%20%20%20%20println!(%22%7B%3A%3F%7D%22%2C%20S)%3B%0A%7D&version=nightly&backtrace=0)

I am going to write this off as a bug that needed to be fixed in both Syntex and rustc. We can add the test later when we support only versions that contain the rustc side of the fix.

**Pull request closed without merging**
